services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: site_php
    volumes:
      - ../site/public:/var/www/html:delegated
    networks:
      - site-net

  nginx:
    image: nginx:stable-alpine
    container_name: site_nginx
    ports:
      - "8080:80"
    volumes:
      - ../site/public:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - site-net

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: site_db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - site-net

networks:
  site-net:
    driver: bridge

volumes:
  db:
    driver: local