openapi: 3.0.3
info: 
  title: Test API for explore
  version: 0.0.1
  description: This is test api for test site. Test version are 0.*.*
  contact:
    name: Developer 1
paths:
  /tests: 
    get:
      summary: Get list of all tests 
      responses:
        "200":
          description: List of all tests was successfully received
          content:
            application/json:

